---

- name: Download Grav
  become: true
  unarchive:
    src: "{{ grav_uri }}"
    dest: /tmp
    remote_src: yes

- name: Deploy Grav (1)
  become: true
  shell: "cp /tmp/grav-admin/webserver-configs/htaccess.txt {{ item }}/.htaccess"
  when: grav_webserver == 'apache'

- name: Deploy Grav (2)
  become: true
  shell: "mv /tmp/grav-admin/* {{ item }}"

- name: Discard archive
  become: true
  file:
    path: /tmp/grav-admin
    state: absent

- name: Set file ownership
  become: true
  file:
    path: "{{ item }}"
    owner: "{{ grav_owner }}"
    group: "{{ grav_group }}"
    recurse: yes

