---


- name: "Testing if {{ item }} is empty"
  find:
    paths: "{{ item }}"
    patterns: '*'
  register: foundfiles

- include_tasks: update.yml
  when: foundfiles.matched > 0

- include_tasks: install.yml
  when: foundfiles.matched == 0
