---

- name: "Ensure Grav's bin/gmp binary is there"
  stat:
    path: "{{ item }}/bin/gpm"
  register: st

- name: "Ensure Grav is current in {{ item }}"
  shell: "bin/gpm -n -q self-upgrade"
  args:
    chdir: "{{ item }}"
  when: st.stat.exists

- name: "Ensure Grav modules are current in {{ item }}"
  shell: "bin/gpm -n -q update"
  args:
    chdir: "{{ item }}"
  when: st.stat.exists
